[tools]
node = "25.4.0"
"ubi:lucasew/workspaced" = "latest"

[env]
_.path = ["./node_modules/.bin"]

[tasks.dev]
run = "vercel dev"

[tasks.build]
run = "npm run build"

[tasks.install]
depends = ["install:*"]

[tasks."install:npm"]
run = "npm install && npx playwright install --with-deps"

[tasks.codegen]
depends = ["codegen:*"]

[tasks."codegen:relay"]
run = "npm run relay"

[tasks.lint]
run = "workspaced codebase lint"

[tasks.fmt]
run = "workspaced codebase format"

[tasks.test]
depends = ["test:*"]

[tasks."test:playwright"]
run = "npx playwright test"

[tasks.ci]
depends = ["lint", "test"]
